import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import { readFileSync } from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	define: {
		"process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
	},
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	treeShaking: true,
	outfile: "main.js",
});

// The Obsidian plugin review rejects bundles that create <script> elements.
// React 19 does so for resource hoisting, so a dependency upgrade can bring
// this back without any change to the plugin's own code.
const assertNoScriptInjection = (outfile) => {
	if (/createElement\(\s*["'`]script["'`]\s*\)/.test(readFileSync(outfile, "utf8"))) {
		throw new Error(`${outfile} creates <script> elements at runtime`);
	}
};

if (prod) {
	await context.rebuild();
	assertNoScriptInjection("main.js");
	process.exit(0);
} else {
	await context.watch();
}

